name: Singularity Build
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

  pull_request:
    paths:
      - Dockerfile


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker container
        run: docker build -t gofflab/qmn .

      - uses: actions/setup-go@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config

      - name: Install Singularity
        env:
          SINGULARITY_VERSION: 3.8.3
          GOPATH: /tmp/go
        run: |
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p $GOPATH/src/github.com/sylabs && \
          cd $GOPATH/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity-ce-${SINGULARITY_VERSION} && \
          ./mconfig -p /usr/local && \
          make -C builddir && \
          sudo make -C builddir install

      - name: Convert to Singularity
        run: sudo singularity build container.sif docker-daemon://gofflab/qmn

      - name: Login and Deploy Container
        # if: github.event_name != 'pull_request'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u chaichontat --password-stdin oras://ghcr.io
          singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest
