name: Singularity Build
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

  pull_request:
    paths:
      - Dockerfile


jobs:
  build-singularity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker container
        run: docker build -t gofflab/qmn22 .

      - name: Convert to Singularity
        run: |
          docker run -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd):/data \
          --privileged -t --rm \
          quay.io/singularity/singularity:v3.10.2 \
          build /data/container.sif docker-daemon://gofflab/qmn22:latest

      - name: Login and Deploy Container
        # if: github.event_name != 'pull_request'
        run: |
          docker run \
          -v $(pwd):/data \
          -t --rm \
          --entrypoint '/bin/bash' \
          --env GITHUB_REPOSITORY=GITHUB_REPOSITORY \
          quay.io/singularity/singularity:v3.10.2 \
          -c 'echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u chaichontat --password-stdin oras://ghcr.io && singularity push /data/container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest'

  build-docker:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ format('${0}-docker', steps.meta.outputs.tags) }}
          labels: ${{ steps.meta.outputs.labels }}