name: Singularity Build
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

  pull_request:
    paths:
      - Dockerfile


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        singularity_version:
          - '3.8.1'

    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    name: Build
    steps:
      - name: Build Container
        run: |
          docker build -t qmn22/${{ github.sha }} .
          sudo singularity build my_container.sif docker-daemon://qmn22/${{ github.sha }}

      - name: Login and Deploy Container
        # if: github.event_name != 'pull_request'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u chaichontat --password-stdin oras://ghcr.io
          singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest