name: Singularity Build
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

  pull_request:
    paths:
      - Dockerfile


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker container
        run: docker build -t gofflab/qmn22 .

      - name: Convert to Singularity
        run: |
          docker run -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd):/data \
          --privileged -t --rm \
          quay.io/singularity/singularity:v3.10.2 \
          build /data/container.sif docker-daemon://gofflab/qmn22:latest

      - name: Login and Deploy Container
        # if: github.event_name != 'pull_request'
        run: |
          docker run \
          -v $(pwd):/data \
          -t --rm \
          --entrypoint '/bin/bash' \
          quay.io/singularity/singularity:v3.10.2 \
          'echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u chaichontat --password-stdin oras://ghcr.io && singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest'
